stations = [
    "Dwarka", "Dwarka Sector 21", "Dwarka Sector 8", "Dwarka Sector 9", "Dwarka Sector 10", 
"Dwarka Sector 11", "Dwarka Sector 12", "Dwarka Sector 13", "Dwarka Sector 14", 
"Dwarka", "Dwarka Mor", "Nawada", "Uttam Nagar West", "Uttam Nagar East", "Janakpuri West", 
"Janakpuri East", "Tilak Nagar", "Subhash Nagar", "Tagore Garden", "Rajouri Garden", 
"Ramesh Nagar", "Moti Nagar", "Kirti Nagar", "Shadipur", "Patel Nagar", "Rajendra Place", 
"Karol Bagh", "Jhandewalan", "Ramakrishna Ashram Marg", "Rajiv Chowk", "Barakhamba Road", 
"Mandi House", "Supreme Court", "Indraprastha", "Yamuna Bank", "Laxmi Nagar", "Nirman Vihar", 
"Preet Vihar", "Karkarduma", "Anand Vihar ISBT", "Kaushambi", "Vaishali", "Akshardham", 
"Mayur Vihar Phase-1", "Mayur Vihar Extension", "New Ashok Nagar", "Noida Sector 15", 
"Noida Sector 16", "Noida Sector 18", "Botanical Garden", "Golf Course", "Noida City Centre", 
"Noida Sector 34", "Noida Sector 52", "Noida Sector 61", "Noida Sector 59", "Noida Sector 62", 
"Noida Electronic City", "Samaypur Badli", "Rohini Sector 18,19", "Haiderpur Badli Mor", "Jahangirpuri", 
"Adarsh Nagar", "Azadpur", "Model Town", "GTB Nagar", "Vishwavidyalaya", "Vidhan Sabha", 
"Civil Lines", "Kashmere Gate", "Chandni Chowk", "Chawri Bazar", "New Delhi", "Rajiv Chowk", 
"Patel Chowk", "Central Secretariat", "Udyog Bhawan", "Lok Kalyan Marg", "Jor Bagh", "INA", 
"AIIMS", "Green Park", "Hauz Khas", "Malviya Nagar", "Saket", "Qutab Minar", "Chattarpur", 
"Sultanpur", "Ghitorni", "Arjangarh", "Guru Dronacharya", "Sikanderpur", "MG Road", "IFFCO Chowk", 
"HUDA City Centre", "Rithala", "Rohini West", "Rohini East", "Pitampura", "Kohat Enclave", 
"Netaji Subhash Place", "Keshav Puram", "Kanhaiya Nagar", "Inderlok", "Shastri Nagar", 
"Pratap Nagar", "Pulbangash", "Tis Hazari", "Shastri Park", "Seelampur", "Welcome", "Shahdara", 
"Mansarovar Park", "Jhilmil", "Dilshad Garden", "Shaheed Nagar", "Raj Bagh", "Shiv Vihar", 
"Satguru Ram Singh Marg", "Ashok Park Main", "Punjabi Bagh", "Shivaji Park", "Madipur", 
"Paschim Vihar East", "Paschim Vihar West", "Peera Garhi", "Udyog Nagar", "Mundka", 
"Mundka Industrial Area", "Ghevra", "Tikri Kalan", "Tikri Border", "Brigadier Hoshiar Singh", 
"Okhla Bird Sanctuary", "Kalindi Kunj", "Jasola Vihar Shaheen Bagh", "Okhla Vihar", 
"Jamia Millia Islamia", "Sukhdev Vihar", "NSIC Okhla", "Nehrun Enclave", "Greater Kailash", 
"Chirag Delhi", "Panchsheel Park", "Hauz Khas", "IIT Delhi", "R.K. Puram", "Munirka", 
"Vasant Vihar", "Terminal 1 IGI Airport", "Sadar Bazar", "Palam", "Dashrathpuri", "Dabri Mor", 
"Janakpuri West", "Majlis Park", "Shalimar Bagh", "Netaji Subhash Place", "Shakurpur", 
"Punjabi Bagh West", "ESI Hospital", "Rajouri Garden", "Maya Puri", "Naraina Vihar", "Delhi Cantt", 
"Durgabai Deshmukh South Campus", "Sir Vishweshwaraiah Moti Bagh", "Bhikaji Cama Place", 
"Sarojini Nagar", "INA", "South Extension", "Lajpat Nagar", "Vinobapuri", "Ashram", 
"Hazrat Nizamuddin", "Mayur Vihar Phase-1", "Mayur Vihar Pocket I", "Trilokpuri Sanjay Lake", 
"East Vinod Nagar", "Mandawali", "IP Extension", "Anand Vihar", "Karkarduma", "Karkarduma Court", 
"Krishna Nagar", "East Azad Nagar", "Welcome", "Jafrabad", "Maujpur", "Gokulpuri", "Johri Enclave", 
"Shiv Vihar", "Lal Quila"

]
